### ISSUE TITLE
Support ARDagent / kickstart

### ISSUE THREAD

**Issue by AllWorkAndNoPlay** [jamf/PPPC-Utility#10]
Be able to add com.apple.screensharing.agent to PPPC-Utility so PPPC-Utility can be used to manage screensharing PPPC settings. 
https://support.apple.com/en-au/HT209161

**Comment by cyrusingraham** [comment]
You should be able to management the screensharing settings already with the PPPC Utility. You can drag and drop the ScreensharingAgent.bundle into the PPPC Utility and set the "Post Events" service to allow. 

The ScreensharingAgent.bundle can be found here:
`/System/Library/CoreServices/RemoteManagement/ScreensharingAgent.bundle`

You can use the following command to open the directory containing the bundle and than drag and drop the bundle into the PPPC Utility:
`open /System/Library/CoreServices/RemoteManagement/`

This is what the profile looks like in the PPPC Utility:
<img width="1011" alt="screen shot 2019-01-25 at 6 42 50 am" src="https://user-images.githubusercontent.com/2578157/51746897-56206b00-206d-11e9-8980-1c8b4b6b3242.png">
