### ISSUE TITLE
Input Monitoring PPPC for Catalina

### ISSUE THREAD

**Issue by BobRe2022** [jamf/PPPC-Utility#109]
When trying to create a PPPC for Wacom tablets for users in in our labs to check input monitoring on OS Catalina computers, it will only allow it for Big Sur and up.  Any way to get PPPC Utility to allow Input Monitoring to be used for Catalina computers as well?

**Comment by macblazer** [comment]
Sadly, Input Monitoring and Screen Capture are `Deny` only in macOS 10.15 (Catalina) for PPPC profiles.   On Catalina, I believe it may need an admin level user on the Mac to consent to the use of these two technologies.

In Big Sur and later, PPPC profiles can specifically allow non-admin Mac users to consent to these technologies.

I think the options allowed in our app are correctly showing the things that can be done.

**Comment by BobRe2022** [comment]
Thank you macblaser for the answer and the quick reply
