### ISSUE TITLE
Property Attributes In PPPC Do Not Match Jamf Pro

### ISSUE THREAD

**Issue by ntruden** [jamf/PPPC-Utility#111]
When the PPPC is uploaded to Jamf Pro, access gets set to 'Allow Standard Users to Allow Access'. You have to "Edit" each privacy setting so Jamf will change it to just "Allow". If this is not done the profile fail when trying to deploy.

**Comment by macblazer** [comment]
We currently think this is a bug in Jamf Pro's API during the upload process.  I am working with others within Jamf to get this sorted out.

**Comment by macblazer** [comment]
This occurs only when "Big Sur Compatibility" is enabled in PPPC Utility, and will be fixed in an upcoming release of Jamf Pro.
