### ISSUE TITLE
Support for new "Screen & System Audio Recording" setting in MacOS 14.2+

### ISSUE THREAD

**Issue by KenMillard-Steampunk** [jamf/PPPC-Utility#126]
Recently noticed that in latest version of MacOS (version 14.2+) that the new version of Microsoft Teams uses permissions that are not available in the current version of PPPC-Utility ("Screen & System Audio Recording").  

<img width="721" alt="image" src="https://github.com/jamf/PPPC-Utility/assets/138230073/1d35f076-5a03-4fb3-8216-aa8c81ad2029">

Here is a screenshot of the privacy setting used by new Teams.  I believe there are other applications that are using this setting as well:

<img width="1240" alt="image" src="https://github.com/jamf/PPPC-Utility/assets/138230073/7ef5d2a8-e03d-47e9-9af0-0625464cb76c">

Is this something that could be supported in future versions?  

Thanks again!  PPPC-Utility is amazing!

**Comment by macblazer** [comment]
@KenMillard-Steampunk There is no key to manage this capability yet.

We can [look here](https://github.com/apple/device-management/blob/release/mdm/profiles/com.apple.TCC.configuration-profile-policy.yaml) in the future to find the key if Apple provides one.

**Comment by aaronclarke** [comment]
I think this is already supported. The names "Screen Recording" and "Screen Recording & System Audio" are just display names for the "[ScreenCapture](https://github.com/apple/device-management/blob/release/mdm/profiles/com.apple.TCC.configuration-profile-policy.yaml#L210)" service, so settings you apply to "Screen Recording" in PPPC will show up in "Screen Recording & System Audio"
