### ISSUE TITLE
Unable to add AppleScript .scpt files

### ISSUE THREAD

**Issue by tempusthales** [jamf/PPPC-Utility#13]
Tried to add an applescript .scpt file, but the file is greyed out and wont let me choose it.

**Comment by watkyn** [comment]
The script needs to be signed, can you verify that it is signed before adding?

**Comment by watkyn** [comment]
We'll look at adding better error messaging so when something fails it isn't such a black box. Closing this out but watch for #37 to be completed which will help with error messages.
