### ISSUE TITLE
SmartBoard Service not adding

### ISSUE THREAD

**Issue by anickless** [jamf/PPPC-Utility#14]
Smart Notebook on Mojave requires the "SmartBoardService" in the Accessibility tab to be enabled.

It is located in "SMART Technologies -> SMART Settings -> Contents -> bin -> SMARTBoardService"

Right now you cannot add it in or drag it in.

**Comment by watkyn** [comment]
We'll look at adding better error messaging so when something fails it isn't such a black box. Closing this out but watch for #37 to be completed which will help with error messages.
