### ISSUE TITLE
App Menu has references to TCCUtility

### ISSUE THREAD

**Issue by drunkonmusic** [jamf/PPPC-Utility#18]
If you click on the PPPC Utility menu you see it still has references to TCC: 
About TCCUtility
Hide TCCUtility
Quit TCCUtility 
![Screenshot 2019-08-28 14 56 47](https://user-images.githubusercontent.com/7939835/63893159-07de9c00-c9af-11e9-9b53-061fd19ae06e.png)

**Comment by mm512** [comment]
Fixed with #19. Thanks, @adku!
