### ISSUE TITLE
10.15 Beta 7 (19A546d) Changes "Apple Events" window size preventing edits

### ISSUE THREAD

**Issue by MrMacintoshBlog** [jamf/PPPC-Utility#20]
After upgrading to 10.15 Beta 7 19A546d the Apple Events window is changed to just a line preventing editing or adding new events.

**Comment by mm512** [comment]
This issue should be fixed with #15

**Comment by mm512** [comment]
@MrMacintoshBlog Please check if you see any issues with the newest release - 1.1.0

**Comment by MrMacintoshBlog** [comment]
I can see the Apple events window now in the new interface. Thanks @mm512!
