### ISSUE TITLE
Cant drag app to PPPC utility window

### ISSUE THREAD

**Issue by GabeShack** [jamf/PPPC-Utility#23]
Im working with Mimio Notebook and it won't allow me to add it to the window with the plus button or with drag and drop.  This may be a duplicate issue since I saw another posting describing the same issue.

**Comment by mm512** [comment]
@GabeShack Please check if you see issues with the newest release - 1.1.0.

**Comment by leegalan** [comment]
I'm having the same issue with Panopto 7.0.0. I'm able to add other apps, but not this one. I've tested it with PPPC Utility 1.1.0.

**Comment by mm512** [comment]
@leegalan Is Panopto an ".app" file or executable? Is it grey out in the file browser window when you click on the plus button?

**Comment by leegalan** [comment]
Panopto is a .app file. It does NOT show up gray when I try to add using the plus button. Refer to the attached screen shot.

![Screen Shot 2019-09-10 at 11 11 35 AM](https://user-images.githubusercontent.com/30468022/64626482-e53f8080-d3bb-11e9-94d1-08b59344ff07.png)

**Comment by GabeShack** [comment]
These executables/or apps Im guessing are just not signed.

Gabe Shackney
Coordinator of Device Operations and Systems Integration
Princeton Public Schools
609-806-4299 x2

On Sep 10, 2019, at 11:03 AM, Michał Matoga <notifications@github.com<mailto:notifications@github.com>> wrote:


@leegalan<https://github.com/leegalan> Is Panopto an ".app" file or executable? Is it grey out in the file browser window when you click on the plus button?

**Comment by leegalan** [comment]
Oh, good to know. let me investigate that...
