### ISSUE TITLE
Failed deployment of configuration profile

### ISSUE THREAD

**Issue by dfuriet** [jamf/PPPC-Utility#24]
Hi

I use Jamf Pro 10.15 and PPPC for accecibility of a wacom driver in Mojave

So when a add a mac in scope of configuration profile, the deployment of configuration profile failed, without error.

I've created a case (JAMF-0767429) on jamf support for this error of deploying profile

Bye

**Comment by esummers** [comment]
Could be #29

**Comment by watkyn** [comment]
Solution provided since the target device did not have user approved MDM profile.
