### ISSUE TITLE
Suggestion: Change label for Jamf Pro Server

### ISSUE THREAD

**Issue by daroloson** [jamf/PPPC-Utility#32]
Suggestion: 'Jamf Pro Server' label be changed to 'Jamf Pro Server URL'

The label suggests that the field wants just  jamf.example.com

**Comment by esummers** [comment]
Adding an example URL in the text field placeholder text would be a good idea.  At the moment it says "[Required]" which is a non-standard use of placeholders.

**Comment by pirkla** [comment]
#34 updates the Jamf Pro Server label to Jamf Pro Server URL
It turns out the placeholder was showing a url in the text field in the storyboard but was being overwritten by the binding to Defaults Controller setting the Null Placeholder to [Required] so fixed that to be the url too.
