### ISSUE TITLE
Enhancement - Save and open a configuration

### ISSUE THREAD

**Issue by jelockwood** [jamf/PPPC-Utility#33]
I would like to be able to build a configuration, upload it, _and_ save it. I would then like to later re-open this configuration and make changes to it - typically the addition of more PPPC settings.

It is highly unlikely that a single computer would not have all the source apps on it and indeed in some cases it might not even be possible to install all the apps on a single computer. Therefore if the config can be saved and reloaded it would be possible to build the settings via several different computers before uploading the complete list to the JSS server. It would also make it possible to load an existing config then update it and upload the new version to the JSS server without having to laboriously repeat previous apps.

**Comment by Bhuvnesh140889** [comment]
I believe you should be able to download the profile on the system, un-sign it, make the changes, re-sign it and deploy it again. 

I came across this video discussing a similar thing - "Roll-Your-Own Configuration Profile | JNUC 2019" - https://www.youtube.com/watch?v=tqF4ls823ig

Commands are at :-
Jamf.it/jnuc2019-ryo

Hope this helps :)

**Comment by jelockwood** [comment]
Whilst what you describe is possible using Apple Configurator I am not sure it is possible with PPPC. The open command is greyed out and drag and drop on to the PPPC icon does not work with a mobileconfig file not even an unsigned one.

Even if we accept it might be possible it clearly is a much more cumbersome approach.

**Comment by macblazer** [comment]
@jelockwood Please check if the v1.2.0 release will meet your needs with the ability to import a profile.  Let us know either way so we can close out this issue, or understand better what needs to still be improved.

**Comment by jelockwood** [comment]
@macblazer 
Thanks for including this enhancement. I tried importing a profile created with an older version of PPPC and it rejected it. I then created a new profile using the same app and setting and then tried importing that and this time it worked.

It was a while ago I created the original one and I cannot remember all the details so I will say that yes the feature works as desired. If I find in future import issues I will raise a new issue but I am happy for this to be closed as complete.

**Comment by pirkla** [comment]
The issue with importing the older version of the profile is most likely due to changes made in the new feature that also corrected the xml structure of profiles. The import process validates that profiles conform to that structure which means it would reject old profiles.

You might be able to upload the old profile by manually changing the top level payload type to Configuration and correct the case on the payload scope as described in this issue: #29 

Hopefully that adds some clarity! 😄

**Comment by jelockwood** [comment]
Yes I suspected that would be the cause. I am therefore happy and closing this issue as resolved.
