### ISSUE TITLE
New entitlement support for macOS 10.15.4??

### ISSUE THREAD

**Issue by everetteallen** [jamf/PPPC-Utility#46]
Apple introduced 4 new items in the Privacy System preferences panel
Screen Recording, Automation, Analytics & Improvements, and Advertising.

In the new days of remote working we need at least a way to allow Screen Recording and these are not currently covered that I can find. Could we get an update to cover either Screen Recording or all of them??
Thanks!

**Comment by watkyn** [comment]
@everetteallen The only options we have for the PPPC-Utility are documented here in the MDM spec:
https://developer.apple.com/documentation/devicemanagement/privacypreferencespolicycontrol/services
There are certain things in System Preferences that are not in the MDM spec, but you can file Feedback with Apple to request changes. Whenever Apple adds more to the spec we will update the utility.
