### ISSUE TITLE
PayloadType value not set to "Configuration"

### ISSUE THREAD

**Issue by chasewillkom** [jamf/PPPC-Utility#48]
The value for the PayloadType key in the root <dict> element isn't being set to "Configuration" when file is saved. Instead, it uses the same value (com.apple.TCC.configuration-profile-policy) for the other PayloadType key that is located in the PayloadContent's <dict> element .

This causes profiles to not be able to be uploaded into Jamf Now's Custom Profiles feature. Jamf Now requires that this "root" PayloadType value must be "Configuration".

https://github.com/jamf/PPPC-Utility/blob/baa8bd589469f09c4575f32c3ec5b6f056617df8/Source/Model/TCCProfile.swift#L123

**Comment by webdawg** [comment]
looks like this effects the machines that i manage too

jamf now osx

**Comment by chasewillkom** [comment]
This is fixed in version 1.2. Thanks!
