### ISSUE TITLE
Anyone having login issues to Jamf Pro 10.23?

### ISSUE THREAD

**Issue by snowtibber** [jamf/PPPC-Utility#65]
PPPC has been working fine for me until the latest Jamf Pro release 10.23, now Check Connection at Upload just doesn't do anything for me. Anyone having this problem too? Thanks.

PPPC Version 1.2.0 (1.2.0-t1588162790)
Jamf Pro 10.23.0-t1595614145

**Comment by slundy** [comment]
Same here, but with jamf cloud.  No matter what i put in the server line it just won't connect, even after saving the creds to the keychain and restarting the PPPC app.

**Comment by ty-wilson** [comment]
I have also seen this issue with the PPPC Utility and Jamf Pro 10.23, Check Connection does not return and allow you to fill in the Payload Name. Tested on both PPPC Utility versions: 1.1.2 and 1.2.0
If I edit my server address to a testing server, such as 10.15, Check Connection works again.
On the other hand, if I close and reopen the Upload window (with 'Save in keychain' selected), and then just click Upload without using Check Connection, the upload works.
