### ISSUE TITLE
Trying to add adagent to grant full disk access

### ISSUE THREAD

**Issue by imasupersadpanda** [jamf/PPPC-Utility#66]
My company is trying to deploy the AccessData agent and it requires full disk access to function as expected, so I'd like to deploy a config profile allowing this via Jamf. After installing the agent on a VM and running the PPPC Utility from there, I am unable to add the **adagent** application to the Applications section in the PPPC Utility. When I use the drag/drop method, the Applications sidebar lights up with the green outline as if it's going to complete the add, but when I release the app, nothing is added. Similarly, using the + button and manually navigating to the app through the file system doesn't work either. I can select the **adagent** app, but after clicking Open, nothing is in the Applications sidebar.

Thoughts?

**Comment by imasupersadpanda** [comment]
Further info. I also tried to do this with the app [Profile Creator](https://github.com/ProfileCreator/ProfileCreator) and received this additional information when I attempted to drag the adagent program into it:
<img width="423" alt="Screen Shot 2020-08-17 at 9 57 01 AM" src="https://user-images.githubusercontent.com/51414781/90410612-34803d80-e070-11ea-85a5-8025ed0ae24a.png">


Any insight on working around an issue like this?

**Comment by macblazer** [comment]
You will need to talk to the developer of that app to have it properly code signed.  As far as I know Apple's TCC framework does not allow for whitelisting apps that do not have correct code signatures.
