### ISSUE TITLE
1.2.1 downloads 1.2.0

### ISSUE THREAD

**Issue by walkintom** [jamf/PPPC-Utility#74]
After downloading latest release [https://github.com/jamf/PPPC-Utility/releases/download/1.2.1/PPPC-Utility.zip] and extracting it from the archive, the application is still version 1.2.0, not 1.2.1.

**Comment by hisaac** [comment]
Whoops! Thanks for the heads up. This was an issue in our CI pipeline. I've re-uploaded the correct binary now, and future releases _should_ work as expected.
