### ISSUE TITLE
Properties Verbiage 

### ISSUE THREAD

**Issue by azbaron** [jamf/PPPC-Utility#79]
"All Files" in the properties fields should be listed as "Full Disk Access", as the verbiage not being identical is rather confusing.
We even had a jamf pro member get confused by this for a minute.

**Comment by watkyn** [comment]
There is a disconnect between the MDM spec and what shows in System Preferences for security and privacy. The MDM spec in this case if called "System Policy All Files". We should maybe consider having a view that mirrors System Preferences, but also has a way to map those descriptions to the MDM spec. Not sure the best way to do that in the UI.

**Comment by ty-wilson** [comment]
Updated #82:
Renamed a few more properties to better reflect their counterparts under System Preferences > Security & Privacy. The MDM Key name was then added to the help text next to each property.
All Files > Full Disk Access
Address Book > Contacts
Calendar > Calendars
Listen Event > Input Monitoring
Screen Capture > Screen Recording
