### ISSUE TITLE
New PPPC Keys available in Big Sur beta 9

### ISSUE THREAD

**Issue by drunkonmusic** [jamf/PPPC-Utility#80]
Hello, I would like to request the addition of the newly released keys for the PPPC settings.  

The new Authorization keys we have been granted are Allow/Deny for the Screen Recording and Input Monitoring.  

There is also the new addition of the AllowStandardUserToSetSystemService which is different than the above model but still applies.  It persists non-admin users to allow access to predefined apps in System Preferences.  

![Screen Shot 2020-09-29 at 1 29 35 PM](https://user-images.githubusercontent.com/7939835/94602212-2f5f0280-025a-11eb-9e94-f688c503c6bf.png)

**Comment by watkyn** [comment]
For Screen Recording and Input Monitoring the values would change to this in the dropdown...

Deny
Allow standard users to approve when prompted

whereas before the only option was to Deny.
