### ISSUE TITLE
Big Sur compatibility mode- incorrect other values

### ISSUE THREAD

**Issue by PhantomPhixer** [jamf/PPPC-Utility#86]
Testing out the Big Sur compatibility setting gives a result that setting allow on a setting that doesn't have the _allow standard users_ setting uploads to jamf with that value set. 
I noticed this setting a profile up that had the screen capture setting in it as well.

![PPPC Utility](https://user-images.githubusercontent.com/16935829/100346003-10bb8480-2fdb-11eb-82c3-9a217a33121d.png)
![Jamf](https://user-images.githubusercontent.com/16935829/100346016-13b67500-2fdb-11eb-823c-48746081c5e7.png)

**Comment by watkyn** [comment]
I believe the PPPC Utility has the correct value in this case. The downloads folder should have the Allow/Deny options and should not have the "Allow standard users to approve".

From the MDM spec only the ListenEvent and the ScreenCapture keys support the "Allow standard users to approve".

I'm going to close this one out but feel free to add more context if I misunderstood the issue.

**Comment by PhantomPhixer** [comment]
I think you have missed the point. in the PPPC utility window it does indeed show the correct value, however when uploaded to jamf it shows the incorrect value as shown in the screen shot. This only happened when Big Sur compatibility was on.

**Comment by watkyn** [comment]
Thanks for the clarification!

**Comment by ty-wilson** [comment]
This is a known issue with Jamf Pro (PI-009068) where the Authorization value is being changed to 'AllowStandardUserToSetSystemService' when the .mobileconfig is uploaded to Configuration Profiles.
The PPPC Utility is still creating the profile with the correct value as 'Allow'.
The workaround in Jamf Pro is to set the value manually back to 'Allow' after upload for now.

**Comment by watkyn** [comment]
Thanks @ty-wilson, closing this out again.
