### ISSUE TITLE
Missing "Full Disk Access"

### ISSUE THREAD

**Issue by dwshore-personal** [jamf/PPPC-Utility#87]
Although there is an "all files" property (in Catalina at least) that doesn't translate to the "Full Disk Access" privacy request. I'm not sure what the correct flag should be though, so I can't help there.

**Comment by watkyn** [comment]
One of the properties in the PPPC Utility is called "Full Disk Access" and this translates into the MDM key named "SystemPolicyAllFiles". 

I believe this should be working as intended, but if not, can you add some more details about what you are seeing that is not working?
