### ISSUE TITLE
BigSur has Screen Recording the app has Screen Capture.

### ISSUE THREAD

**Issue by willgonz** [jamf/PPPC-Utility#89]
There is no setting on Big Sur for Screen Capture. It is named "Screen Recording"

**Comment by watkyn** [comment]
Correct. The MDM Key is called "ScreenCapture" and in System Preferences it is called "Screen Recording". The unreleased version of the utility has some updates showing the System Preferences equivalent to the MDM key so it will be easier to verify those things in the future.
