### ISSUE TITLE
Example images are misleading.

### ISSUE THREAD

**Issue by craigsadler** [jamf/PPPC-Utility#9]
Since Jamf supplies this profile, a much better example images would show an actual application **without** reference to the Jamf binaries... to avoid confusion and misdirection.

**Comment by cyrusingraham** [comment]
Thank you for the feedback. The example profiles in the images are actually not supplied by Jamf automatically. The profile automatically deployed by the Jamf Pro Server does not grant the binary or agent access to Finder or System Events. That being said I can see how it is confusing. We will look at using a different example for the screenshots in the next release.
