### ISSUE TITLE
Big Sur Toggle Makes everything "Let Standard Users Approve"

### ISSUE THREAD

**Issue by willgonz** [jamf/PPPC-Utility#90]
Not all options allow for "Let Standard Users Approve"  When you Upload to JAMF it will error out.  You must edit the "Configuration Profile" in JAMF and then each "App or Service" you must click edit and JAMF will auto correct it.

**Comment by PhantomPhixer** [comment]
same as [this one](https://github.com/jamf/PPPC-Utility/issues/86) I think?

**Comment by watkyn** [comment]
Yes, that is the same issue. It is a known issue in Jamf Pro and we won't be able to fix it from the PPPC-Utility side of things.
Jamf Pro (PI-009068)
