### ISSUE TITLE
Removing apps from Apple Events always removes the first item

### ISSUE THREAD

**Issue by LGriffioen** [jamf/PPPC-Utility#95]
##### Steps to Reproduce

1. Open up an application
2. drag a few apps into the Apple events panel
3. select one of the apps that's not first in the list
4. click the `-` button

##### Expected Results
the selected item should be removed

##### Actual Results
the first item is removed

----

###### Build
1.3.0

###### Mac OS
11.3.1

**Comment by ty-wilson** [comment]
This is a duplicated of #83

**Comment by macblazer** [comment]
This has already been fixed as part of #83 and will be included in the next release.
