### ISSUE TITLE
Unable to drag multiple apps into Apple Events at once

### ISSUE THREAD

**Issue by LGriffioen** [jamf/PPPC-Utility#96]
##### Steps to Reproduce

1. Add an app to the applications view
2. select a few different apps (all of iWork for example)
3. drag them into the apple events area

##### Expected Results
add all of the items that were dragged in

##### Actual Results
only adds the first item in the list

----

###### Build
1.3.0

###### Mac OS
11.3.1

**Comment by macblazer** [comment]
This has already been fixed as part of #85 and will be included in the next release.
