### ISSUE TITLE
Import to Microsoft Endpoint Manager

### ISSUE THREAD

**Issue by kevets** [jamf/PPPC-Utility#97]
This application provides me with what looks like a perfect set of preferences which I would import into our MDM of choice (Intune). Is there a trick or way to bring this into a more general format that other MDM can process? I'm getting validation failed when attempting to import the straight XML.

https://docs.microsoft.com/en-us/mem/intune/configuration/custom-settings-macos

**Comment by macblazer** [comment]
The config profile saved by PPPC Utility should be standard following Apples guidelines.  Does Intune tell you exactly what part of the profile is failing validation?

**Comment by FlynnLives** [comment]
You should be able to upload the mobileconfig as is  as it is already xml/plain text not binary (open it in text editor)

**Comment by majorsl** [comment]
I know this issue is pretty stale, but we've been using PPPC-Utility very successfully Intune for quite some time. As noted, just save the mobileconfig and upload as a custom configuration profile in Intune.

**Comment by macblazer** [comment]
Closing due to independent confirmation that the profiles can be uploaded into Intune aka Microsoft Endpoint Manager.
