### ISSUE TITLE
AllowStandardUserToSetSystemService

### ISSUE THREAD

**Issue by FlynnLives** [jamf/PPPC-Utility#98]
Ive seen a few other issues posted where people had a drop down for "big sur compatability" but that does not seem to be a option anymore? 

https://github.com/jamf/PPPC-Utility/issues/80 made it sound like it would be in the dropdown for the permission, screen capture for example, but the only option is denied. 

Is there a way to set AllowStandardUserToSetSystemService or would I need to manually edit the mobileconfig after I make it in PPPC-Utility?

**Comment by watkyn** [comment]
There is a switch in the upper right that will turn on Big Sur Compatibility. Once that is toggled on, you should see the option you are looking for in Screen Capture.
